<?php

namespace Database\Seeders;

use App\Models\ProductVariantItem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductVariantItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ProductVariantItem::insert([
            [
                'product_variant_id' => 3,
                'name' => 'Black',
                'price' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 3,
                'name' => 'Grey',
                'price' => 0,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 4,
                'name' => 'Blue',
                'price' => 0,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 4,
                'name' => 'Purple',
                'price' => 0,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 4,
                'name' => 'Space Gray',
                'price' => 0,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 5,
                'name' => '128GB',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 5,
                'name' => '256GB',
                'price' => 15,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 5,
                'name' => '512GB',
                'price' => 20,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 6,
                'name' => 'Midnight',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 6,
                'name' => 'Silver',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 7,
                'name' => 'Black',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 7,
                'name' => 'Silver',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 8,
                'name' => 'Cosmic Orange',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 8,
                'name' => 'Deep Blue',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 8,
                'name' => 'Silver',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 9,
                'name' => '512GB',
                'price' => 20,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 9,
                'name' => '256GB',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 9,
                'name' => '1TB',
                'price' => 30,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 9,
                'name' => '2TB',
                'price' => 40,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 10,
                'name' => 'White',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 10,
                'name' => 'Blue',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 10,
                'name' => 'Gray',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 11,
                'name' => 'Arctic Dawn',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 11,
                'name' => 'Black Eclipse',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 11,
                'name' => 'Black Eclipse Midnight Ocean',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 12,
                'name' => '12/256GB',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 12,
                'name' => '12/512GB',
                'price' => 20,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 12,
                'name' => '16/512GB',
                'price' => 30,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 13,
                'name' => 'Obsidian',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 13,
                'name' => 'Porcelain',
                'price' => 10,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 14,
                'name' => '16/256GB',
                'price' => 10,
                'is_default' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_variant_id' => 14,
                'name' => '16/512GB',
                'price' => 20,
                'is_default' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
